kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.partner.outlook.cn:587'
      smtp_from: 'xxxxxx@gmail.com'
      smtp_auth_username: 'xxxxxx@gmail.com'
      smtp_auth_password: 'xxxxxx'
      smtp_require_tls: true

    templates:
      - '/etc/alertmanager/template/*.tmpl'

    route:
      group_by: [cluster, alertname]
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 30m
      receiver: Default-Receiver
      routes:
      - receiver: 'Email_Alert'
        match:
          namespace: 'testing'

    receivers:
    - name: 'Default-Receiver'
      email_configs:
      - to: '1316163109@qq.com'
        send_resolved: true 

    - name: 'Email_Alert'
      email_configs:
      - to: '540855184@qq.com'
        html: '{{ template "node.email.default.html" . }}'
        headers: { Subject: "[{{ .Status | toUpper }}] {{ .CommonLabels.severity }}: {{ .CommonAnnotations.summary }}" }
        send_resolved: true 
