kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.partner.outlook.cn:587'
      smtp_from: 'yingtao.dong@bespinglobal.cn'
      smtp_auth_username: 'yingtao.dong@bespinglobal.cn'
      smtp_auth_password: 'DANyi1314.com'
      smtp_require_tls: true

    templates:
      - '/etc/alertmanager/templates/*.tmpl'

    route:
      group_by: ['alertname']
      group_wait: 30s
      group_interval: 1m
      repeat_interval: 30m
      receiver: Email_Alert

    receivers:
    - name: 'Email_Alert'
      email_configs:
      - to: '540855184@qq.com'
        html: '{{ template "email.html" . }}'
        headers: { Subject: "[{{ .Status | toUpper }}] {{ .CommonLabels.severity }}: {{ .CommonAnnotations.summary }}" }
        send_resolved: true 
