kind: ConfigMap
apiVersion: v1
metadata:
  name: email-config
  namespace: monitoring
data:
  node.email.default.tmpl: |-
    {{ define "node.email.default.html" }}
      {{ if gt (len .Alerts.Firing) 0 }}
        [{{ .Alerts.Firing | len }}] Firing
      {{ end }}

    {{ range .Alerts.Firing }}
    <pre>
    告警实例: {{ .Labels.instance }}
    告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
    告警级别: {{ .Labels.severity }}
    告警信息: {{ .Annotations.summary }}
    告警详情: {{ .Annotations.description }}
    告警状态: {{ .Status }}
    </pre>
    {{ end }}

    {{ if gt (len .Alerts.Resolved) 0 }}
      {{ if gt (len .Alerts.Firing) 0 }}
      {{ end }}
      [{{ .Alerts.Resolved | len }}] Resolved
    {{ end }}

    {{ range .Alerts.Resolved }}
    <pre>
    告警实例: {{ .Labels.instance }}
    告警时间: {{ .StartsAt.Format "2006-01-02 15:04:05" }}
    恢复时间: {{ .EndsAt.Format "2006-01-02 15:04:05" }}
    告警级别: {{ .Labels.severity }}
    告警信息: {{ .Annotations.summary }}
    告警详情: {{ .Annotations.description }}
    告警状态: {{ .Status }}
    </pre>
    {{ end }}
    {{ end }}
